import { describe, expect, it } from 'vitest';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { mkdtemp, readFile, stat, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { loadConfig } from '../src/config.js';
import { SenjaClient } from '../src/api/client.js';
import {createApp} from '../src/app.js';import {connect as slipwayConnect} from '@thenavidm/slipway/testing';

/** The write policy comes from the environment on Slipway, as it does in use: this is the one a config describes. */
function policy(prefix:string,config:{readOnly?:boolean;allowDestructive?:boolean;auditPath?:string}):Record<string,string>{return{...(config.readOnly?{[`${prefix}_READ_ONLY`]:'1'}:{}),...(config.allowDestructive===false?{[`${prefix}_ALLOW_DESTRUCTIVE`]:'0'}:{}),...(config.auditPath?{[`${prefix}_AUDIT_LOG`]:config.auditPath}:{})};}
/** Slipway's schema check answers in the MCP SDK's own plain text, "Input validation error: …"; these tests read every error as JSON, so it is wrapped as {error}. */
function jsonError(r:any){const text=r.content?.[0]?.text??'';try{JSON.parse(text);return r;}catch{return{...r,content:[{type:'text',text:JSON.stringify({error:text})}]};}}
/** The SDK client's calls these tests were written against, over the real Slipway server. A hidden tool is a protocol error there; it comes back as the error result a client sees. */
function adapt(mcp:Awaited<ReturnType<typeof slipwayConnect>>){return{listTools:async()=>({tools:await mcp.listTools()}),callTool:async({name,arguments:args}:{name:string;arguments?:Record<string,unknown>}):Promise<any>=>{try{const r:any=await mcp.callTool(name,args??{});return r.isError?jsonError(r):r;}catch(e){return{isError:true,content:[{type:'text',text:JSON.stringify({error:(e as Error).message})}]};}},close:()=>mcp.close()};}
/** One tool call through the real server, as the 2.x guard-and-handler helper made it: the result's data, or its error thrown. */
async function viaServer(prefix:string,config:any,client:any,name:string,args:Record<string,unknown>):Promise<any>{const mcp=await slipwayConnect(createApp({context:()=>({config,client})}),{env:policy(prefix,config)});try{const r:any=await mcp.callTool(name,args);const text=(r.content as any[])?.[0]?.text??'';if(r.isError)throw new Error(text);try{return JSON.parse(text);}catch{return text;}}finally{await mcp.close();}}

type Call = {url:URL; init:RequestInit};
async function fixture(options: {readOnly?:boolean; key?:boolean; responder?:(call:Call,index:number)=>Response|Promise<Response>} = {}) {
  const calls:Call[]=[];
  const config=loadConfig({SENJA_MIN_REQUEST_INTERVAL_MS:'0', ...(options.key===false?{}:{SENJA_API_KEY:'fixture-key-a'}), ...(options.readOnly?{SENJA_READ_ONLY:'1'}:{})});
  const fetcher=(async(url:any,init:RequestInit)=>{const call={url:new URL(String(url)),init};calls.push(call);return options.responder?.(call,calls.length-1)??Response.json({ok:true});}) as typeof fetch;
  const api=new SenjaClient(config,fetcher);
  const mcp=await slipwayConnect(createApp({context:()=>({config,client:api})}),{env:policy('SENJA',config)});
  const client=adapt(mcp);
  const call=async(name:string,args:Record<string,any>={})=>{const result=await client.callTool({name,arguments:args});const value=JSON.parse((result.content as any[])[0].text);return {result,value};};
  return {client,api,calls,call,close:()=>mcp.close()};
}

describe('current Senja request contract and shared policy',()=>{
  it('discovers12 shared tools,6 reads and6 confirmed operations with no credential',async()=>{const f=await fixture({key:false});try{const {tools}=await f.client.listTools();expect(tools).toHaveLength(12);expect(tools.filter(t=>t.annotations?.readOnlyHint)).toHaveLength(6);expect(tools.filter(t=>(t.inputSchema.properties as any)?.confirm)).toHaveLength(6);expect((await f.call('list_accounts')).value).toEqual({accounts:[]});expect(f.calls).toHaveLength(0);}finally{await f.close();}});
  it('uses native limit/lang/sort/order/query and repeated tags',async()=>{const f=await fixture({responder:()=>Response.json({total:0,testimonials:[]})});try{expect((await f.call('list_testimonials',{limit:25,lang:'en',sort:'rating',order:'asc',query:'onboarding',tags:['product','service'],approved:false,page:2})).result.isError).toBeFalsy();const c=f.calls[0]!;expect(c.url.origin).toBe('https://api.senja.io');expect(c.url.pathname).toBe('/v1/testimonials');expect(c.url.searchParams.get('limit')).toBe('25');expect(c.url.searchParams.get('lang')).toBe('en');expect(c.url.searchParams.getAll('tags')).toEqual(['product','service']);expect(c.url.searchParams.get('approved')).toBe('false');expect((c.init.headers as any).Authorization).toBe('Bearer fixture-key-a');expect(c.init.redirect).toBe('error');}finally{await f.close();}});
  it.each([{per_page:25},{language:'en'},{sort:'date_desc'},{tags:'product'}])('rejects stale list arguments%j before network',async args=>{const f=await fixture();try{expect((await f.call('list_testimonials',args)).result.isError).toBe(true);expect(f.calls).toHaveLength(0);}finally{await f.close();}});
  it('rejects obsolete create fields before network',async()=>{const f=await fixture();try{expect((await f.call('create_testimonial',{name:'Fixture Person',text:'Fixture statement',confirm:true})).result.isError).toBe(true);expect(f.calls).toHaveLength(0);}finally{await f.close();}});
  it('forwards the actual native create body including media and customer fields',async()=>{const f=await fixture({responder:()=>Response.json({message:'Testimonial created',id:'fixture-id'})});try{const args={type:'text',customer_name:'Fixture Person',text:'Existing fixture statement',approved:false,tags:['fixture'],customer_url:'https://example.com',media:[{url:'https://example.com/image.png',type:'image',alt:'Fixture'}],confirm:true};expect((await f.call('create_testimonial',args)).value.id).toBe('fixture-id');expect(JSON.parse(f.calls[0]!.init.body as string)).toEqual((({confirm,...rest})=>rest)(args));}finally{await f.close();}});
  it('preserves approved:false on a native PATCH',async()=>{const f=await fixture();try{expect((await f.call('update_testimonial',{testimonial_id:'fixture-id',approved:false,confirm:true})).result.isError).toBeFalsy();expect(f.calls[0]!.init.method).toBe('PATCH');expect(JSON.parse(f.calls[0]!.init.body as string)).toEqual({approved:false});}finally{await f.close();}});
  it.each([{}, {text:'unsupported edit'}, {add_tags:[]}, {add_tags:['same'],remove_tags:['same']}])('refuses empty/unsupported/contradictory PATCH%j',async body=>{const f=await fixture();try{expect((await f.call('update_testimonial',{testimonial_id:'fixture-id',...body,confirm:true})).result.isError).toBe(true);expect(f.calls).toHaveLength(0);}finally{await f.close();}});
  it('does not create, tag, delete, invite or export without confirmation',async()=>{const f=await fixture();try{for(const[name,args]of[['create_testimonial',{type:'text',customer_name:'Fixture'}],['update_testimonial',{testimonial_id:'fixture-id',approved:true}],['delete_testimonial',{testimonial_id:'fixture-id'}],['send_invites',{form_id:'fixture-form',recipients:[{email:'fixture@example.com'}]}],['export_testimonials',{output_file:'/private/tmp/never-created-senja.json'}]]as const){expect((await f.call(name,args)).result.isError).toBe(true);}expect(f.calls).toHaveLength(0);}finally{await f.close();}});
  it('hides writes and refuses a direct hidden-tool call in read-only mode',async()=>{const f=await fixture({readOnly:true});try{expect((await f.client.listTools()).tools).toHaveLength(6);expect(JSON.stringify((await f.call('send_invites',{form_id:'fixture-form',recipients:[{email:'fixture@example.com'}],confirm:true})).value)).toMatch(/READ_ONLY|not found/);expect(f.calls).toHaveLength(0);}finally{await f.close();}});
  it('uses the selected form and retains skipped invite receipts without retrying',async()=>{const receipt={sent:1,skipped:[{email:'fixture@example.com',reason:'already_invited'}]};const f=await fixture({responder:()=>Response.json(receipt)});try{const {value}=await f.call('send_invites',{form_id:'fixture-form',recipients:[{email:'fixture@example.com'}],confirm:true});expect(value).toEqual(receipt);expect(f.calls).toHaveLength(1);expect(JSON.parse(f.calls[0]!.init.body as string)).toEqual({form_id:'fixture-form',recipients:[{email:'fixture@example.com'}]});}finally{await f.close();}});
  it('rejects duplicate invite emails and101 recipients locally',async()=>{const f=await fixture();try{for(const recipients of [[{email:'fixture@example.com'},{email:'FIXTURE@example.com'}],Array.from({length:101},(_,i)=>({email:`fixture${i}@example.com`}))])expect((await f.call('send_invites',{form_id:'fixture-form',recipients,confirm:true})).result.isError).toBe(true);expect(f.calls).toHaveLength(0);}finally{await f.close();}});
  it('supports a mutually exclusive native payload/file/flag contract',async()=>{const f=await fixture();try{expect((await f.call('create_testimonial',{payload:{type:'text',customer_name:'Fixture'},customer_name:'Different',confirm:true})).result.isError).toBe(true);expect(f.calls).toHaveLength(0);}finally{await f.close();}});
  it('rejects unknown methods, traversal and arbitrary hosts',async()=>{const f=await fixture();try{for(const path of ['/testimonials/..','/testimonials/x%2Fy','https://example.com','/unsupported'])await expect(f.api.request('GET',path)).rejects.toThrow();expect(f.calls).toHaveLength(0);}finally{await f.close();}});
  it('does not retry429, invalid JSON or an unknown network outcome',async()=>{for(const responder of [()=>new Response('limited',{status:429}),()=>new Response('not json'),()=>{throw Error('fixture transport failed');}]){const f=await fixture({responder});try{expect((await f.call('create_testimonial',{type:'text',customer_name:'Fixture',confirm:true})).result.isError).toBe(true);expect(f.calls).toHaveLength(1);}finally{await f.close();}}});
  it('redacts the selected fixture key in provider errors',async()=>{const f=await fixture({responder:()=>Response.json({error:'fixture-key-a'},{status:403})});try{const {value}=await f.call('list_links');expect(JSON.stringify(value)).not.toContain('fixture-key-a');expect(JSON.stringify(value)).toContain('[redacted]');}finally{await f.close();}});
});

describe('isolated project profiles and reviewed batches',()=>{
  it('named profiles never inherit a global key',()=>{const c=loadConfig({SENJA_API_KEY:'global-fixture',SENJA_ACCOUNTS:'[{"name":"explicit"}]'});expect(c.accounts[0]!.apiToken).toBe('');});
  it.each([{SENJA_ACCOUNTS:'[{"name":"a"},{"name":"a"}]'},{SENJA_API_KEY:'fixture',SENJA_TOKEN_FILE:'/private/tmp/fixture'},{SENJA_ACCOUNTS:'[{"name":"a","api_key":"fixture","other":"x"}]'}])('refuses ambiguous profile settings%j',env=>expect(()=>loadConfig(env)).toThrow());
  it('prevalidates every batch task before network',async()=>{const f=await fixture();try{const tasks=[{tool:'create_testimonial',arguments:{type:'text',customer_name:'Fixture'}},{tool:'update_testimonial',arguments:{testimonial_id:'fixture-id',text:'unsupported'}}];expect((await f.call('preview_testimonial_batch',{tasks})).result.isError).toBe(true);expect(f.calls).toHaveLength(0);}finally{await f.close();}});
  it('binds exact request contents and order to the local review hash',async()=>{const f=await fixture();try{const tasks=[{tool:'create_testimonial',arguments:{type:'text',customer_name:'Fixture'}}];const p=await f.call('preview_testimonial_batch',{tasks});expect(p.result.isError).toBeFalsy();expect(f.calls).toHaveLength(0);const changed=[{tool:'create_testimonial',arguments:{type:'text',customer_name:'Changed'}}];expect((await f.call('submit_testimonial_batch',{tasks:changed,review_sha256:p.value.reviewSha256,confirm:true})).result.isError).toBe(true);expect(f.calls).toHaveLength(0);}finally{await f.close();}});
  it('stops at a failure and retains known outcomes without retry/rollback',async()=>{const f=await fixture({responder:(_,i)=>i===1?Response.json({error:'fixture failure'},{status:500}):Response.json({id:'created-fixture'})});try{const tasks=Array.from({length:3},(_,i)=>({tool:'create_testimonial',arguments:{type:'text',customer_name:`Fixture${i}`}}));const p=await f.call('preview_testimonial_batch',{tasks});const {result,value}=await f.call('submit_testimonial_batch',{tasks,review_sha256:p.value.reviewSha256,confirm:true});expect(result.isError).toBe(true);const receipt=JSON.parse(value.error);expect(receipt.failedIndex).toBe(1);expect(receipt.knownResults).toHaveLength(1);expect(receipt.unattemptedIndices).toEqual([2]);expect(f.calls).toHaveLength(2);}finally{await f.close();}});
});

describe('bounded private testimonial export',()=>{
  it('resumes inside the requested first page using the explicit receipt offset',async()=>{const dir=await mkdtemp(join(tmpdir(),'senja-export-'));const f=await fixture({responder:()=>Response.json({total:3,testimonials:[{id:'one'},{id:'two'},{id:'three'}]})});try{const {result,value}=await f.call('export_testimonials',{output_file:join(dir,'resumed.json'),page:4,limit:3,start_offset:2,max_items:1,confirm:true});expect(result.isError).toBeFalsy();expect(value.items).toBe(1);expect(value.continuation).toEqual({page:5,offset:0,limit:3});expect(JSON.parse(await readFile(join(dir,'resumed.json'),'utf8')).testimonials).toEqual([{id:'three'}]);expect(f.calls[0]!.url.searchParams.get('page')).toBe('4');}finally{await f.close();await rm(dir,{recursive:true,force:true});}});
  it('stops at the local page budget without asserting completeness',async()=>{const dir=await mkdtemp(join(tmpdir(),'senja-export-'));const f=await fixture({responder:()=>Response.json({total:1,testimonials:[{id:'fixture'}]})});try{const {value}=await f.call('export_testimonials',{output_file:join(dir,'bounded.json'),limit:1,max_pages:2,confirm:true});expect(value.requests).toBe(2);expect(value.completeWithinRequestedFilters).toBe(false);expect(value.continuation).toEqual({page:3,offset:0,limit:1});expect(f.calls).toHaveLength(2);}finally{await f.close();await rm(dir,{recursive:true,force:true});}});
  it('refuses an invalid resume offset before file creation or network',async()=>{const f=await fixture();try{expect((await f.call('export_testimonials',{output_file:'/private/tmp/never-created-senja-offset.json',limit:1,start_offset:1,confirm:true})).result.isError).toBe(true);expect(f.calls).toHaveLength(0);}finally{await f.close();}});
  it('treats total as a page count and stops on the short page',async()=>{const dir=await mkdtemp(join(tmpdir(),'senja-export-'));const f=await fixture({responder:(_,i)=>Response.json(i===0?{total:2,testimonials:[{id:'one'},{id:'two'}]}:{total:1,testimonials:[{id:'three'}]})});try{const output_file=join(dir,'proof.json');const {result,value}=await f.call('export_testimonials',{output_file,limit:2,confirm:true});expect(result.isError).toBeFalsy();expect(value.requests).toBe(2);expect(value.items).toBe(3);expect(value.completeWithinRequestedFilters).toBe(true);expect(f.calls.map(c=>c.url.searchParams.get('page'))).toEqual(['1','2']);expect(JSON.parse(await readFile(output_file,'utf8')).testimonials).toHaveLength(3);if(process.platform!=='win32')expect((await stat(output_file)).mode&0o777).toBe(0o600);}finally{await f.close();await rm(dir,{recursive:true,force:true});}});
  it('caps items within a page and reports the exact continuation offset',async()=>{const dir=await mkdtemp(join(tmpdir(),'senja-export-'));const f=await fixture({responder:()=>Response.json({total:3,testimonials:[{id:'one'},{id:'two'},{id:'three'}]})});try{const {value}=await f.call('export_testimonials',{output_file:join(dir,'proof.json'),limit:3,max_items:2,confirm:true});expect(value.items).toBe(2);expect(value.completeWithinRequestedFilters).toBe(false);expect(value.continuation).toEqual({page:1,offset:2,limit:3});expect(f.calls).toHaveLength(1);}finally{await f.close();await rm(dir,{recursive:true,force:true});}});
  it('does not overwrite an existing private file or make a request',async()=>{const dir=await mkdtemp(join(tmpdir(),'senja-export-'));const f=await fixture();try{const output_file=join(dir,'existing.json');await writeFile(output_file,'original');expect((await f.call('export_testimonials',{output_file,confirm:true})).result.isError).toBe(true);expect(f.calls).toHaveLength(0);expect(await readFile(output_file,'utf8')).toBe('original');}finally{await f.close();await rm(dir,{recursive:true,force:true});}});
  it('removes only its new partial file after an invalid native receipt',async()=>{const dir=await mkdtemp(join(tmpdir(),'senja-export-'));const f=await fixture({responder:()=>Response.json({total:100,data:[{id:'wrong-envelope'}]})});try{const output_file=join(dir,'partial.json');expect((await f.call('export_testimonials',{output_file,confirm:true})).result.isError).toBe(true);await expect(stat(output_file)).rejects.toThrow();expect(f.calls).toHaveLength(1);}finally{await f.close();await rm(dir,{recursive:true,force:true});}});
});
