import{open,lstat}from'node:fs/promises';import{constants}from'node:fs';import{isAbsolute}from'node:path';
import{selectAccount,type Account,type Config}from'../config.js';import{SenjaError,UsageError}from'./errors.js';import operations from'../tools/operations.json'with{type:'json'};
export type Json=Record<string,any>;export type QueryParam={name:string;value:unknown;explode?:boolean};const MAX=5*1048576;
const routes=operations.map(o=>({method:o.method,regex:new RegExp('^'+o.path.replace(/[.*+?^$()|[\]\\]/g,'\\$&').replace(/\{[^}]+\}/g,'([^/]+)')+'$')}));
export class SenjaClient{
 private tokens=new Map<string,string>();private schedule:Promise<void>=Promise.resolve();private nextAt=0;
 constructor(readonly config:Config,private readonly fetcher:typeof fetch=fetch,private readonly sleep:(ms:number)=>Promise<void>=ms=>new Promise(r=>setTimeout(r,ms))){}
 redactText(text:string){for(const secret of [...this.config.accounts.map(a=>a.apiToken),...this.tokens.values()].filter(Boolean).flatMap(v=>[v,Buffer.from(v+':').toString('base64')]).sort((a,b)=>b.length-a.length))text=text.split(secret).join('[redacted]');return text.replace(/https?:\/\/[^\s"<>]*(?:X-Amz-Signature|[?&](?:token|signature|sig|key|access_token)=)[^\s"<>]*/gi,'[private credential URL]');}
 sanitize(v:unknown):unknown{if(typeof v==='string')return this.redactText(v);if(Array.isArray(v))return v.map(x=>this.sanitize(x));if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,/^(password|secret|api_key|signing_key|api_token|token|publicToken|access_token|refresh_token|authorization|client_secret)$/i.test(k)?'[redacted]':this.sanitize(x)]));return v;}
 private async token(a:Account){if(this.tokens.has(a.name))return this.tokens.get(a.name)!;let token=a.apiToken;if(a.tokenFile){let file;try{if(!isAbsolute(a.tokenFile))throw Error();if(!(await lstat(a.tokenFile)).isFile())throw Error();file=await open(a.tokenFile,constants.O_RDONLY|(constants.O_NOFOLLOW??0));const stat=await file.stat();if(!stat.isFile()||stat.size>65536||(process.platform!=='win32'&&((stat.mode&0o077)||stat.uid!==process.getuid?.())))throw Error();token=(await file.readFile('utf8')).trim();}catch{throw new SenjaError('Cannot read the private Senja token file; use an absolute owner-only regular token-only file at most 64 KiB.',0,'CONFIG');}finally{await file?.close();}}if(!token||/[\r\n]/.test(token))throw new SenjaError('No valid API key configured for the selected account profile. Run senja-cli login.',0,'CONFIG');this.tokens.set(a.name,token);return token;}
 private async pace(){const next=this.schedule.catch(()=>{}).then(async()=>{const delay=Math.max(0,this.nextAt-Date.now());if(delay)await this.sleep(delay);this.nextAt=Date.now()+this.config.minIntervalMs;});this.schedule=next;await next;}
 private async bytes(response:Response){const chunks:Uint8Array[]=[];let total=0;const reader=response.body?.getReader();if(reader)try{for(;;){const part=await reader.read();if(part.done)break;total+=part.value.byteLength;if(total>MAX){await reader.cancel();throw new SenjaError('Response exceeds the 5 MiB local cap; no automatic retry.');}chunks.push(part.value);}}finally{reader.releaseLock();}return Buffer.concat(chunks);}
 async request(method:string,path:string,query:QueryParam[]=[],body?:unknown,hint?:string):Promise<any>{
  if(!routes.some(r=>r.method===method&&r.regex.test(path))||/[?#\\]/.test(path)||/%2f|%5c|%00/i.test(path)||path.split('/').some(s=>['.','..'].includes(decodeURIComponent(s))))throw new UsageError('Unsupported Senja API method or path.');
  const a=selectAccount(this.config,hint);const url=new URL('/v1'+path,'https://api.senja.io');for(const p of query){if(p.value===undefined||p.value===null)continue;if(Array.isArray(p.value)){for(const v of p.value)url.searchParams.append(p.name,String(v));}else if(typeof p.value==='object')throw new UsageError('Object query parameters are unsupported.');else url.searchParams.set(p.name,String(p.value));}
  const secret=await this.token(a);const headers:Record<string,string>={Accept:'application/json','User-Agent':'Navid Media Senja MCP CLI/2.0.0 (https://navid.me)',Authorization:'Bearer '+secret};
  const encoded=body===undefined?undefined:JSON.stringify(body);if(encoded!==undefined){if(Buffer.byteLength(encoded)>1048576)throw new UsageError('Request exceeds 1 MiB JSON limit.');headers['Content-Type']='application/json';}
  await this.pace();let response:Response;try{response=await this.fetcher(url,{method,redirect:'error',signal:AbortSignal.timeout(this.config.timeoutMs),headers,...(encoded===undefined?{}:{body:encoded})});}catch{throw new SenjaError('Senja request failed or timed out. Its outcome may be unknown; no automatic retry. Inspect provider state before deliberately repeating.',0,'NETWORK');}
  const bytes=await this.bytes(response);if(!response.ok){let detail='';try{detail=JSON.stringify(this.sanitize(JSON.parse(bytes.toString('utf8')))).slice(0,1000);}catch{}throw new SenjaError('Senja API '+response.status+(response.status===429?' rate limit':'')+(detail?': '+detail:''),response.status,response.status===429?'RATE_LIMIT':[401,403].includes(response.status)?'AUTH':'API_ERROR');}
  if(response.status===204||!bytes.length)return{http_status:response.status,success:true};
  let parsed;try{parsed=JSON.parse(bytes.toString('utf8'));}catch{throw new SenjaError('Senja returned a non-JSON response; no automatic retry.');}if(parsed===null||typeof parsed!=='object')throw new SenjaError('Invalid Senja JSON response.');return response.status===202?{accepted:true,http_status:202,result:parsed}:parsed;
 }
}
