import operationsData from'./operations.json'with{type:'json'};import provenance from'./provenance.json'with{type:'json'};import{Ajv,type ValidateFunction}from'ajv';import addFormats from'ajv-formats';import{open,lstat,unlink}from'node:fs/promises';import{constants}from'node:fs';import{isAbsolute}from'node:path';import{createHash}from'node:crypto';
import{SenjaClient,type Json,type QueryParam}from'../api/client.js';import{SenjaError,UsageError}from'../api/errors.js';import{selectAccount,type Config}from'../config.js';import type { Risk } from "@thenavidm/slipway";
export type Operation={name:string;operationId:string;title:string;description:string;method:string;path:string;group:string;risk:Risk;params:{name:string;key:string;in:string;required:boolean;schema:Json;style:string;explode:boolean}[];bodySchema:Json|null;bodyRequired:boolean;privateOutput:boolean};
export type ToolSpec={name:string;title:string;description:string;group:string;inputSchema:Json;risk:Risk;handler:(args:Json,client:SenjaClient)=>Promise<unknown>};
const operations=operationsData as unknown as Operation[];const ajv=new Ajv({allErrors:true,strict:false,formats:{int64:true}});(addFormats as unknown as(a:Ajv)=>void)(ajv);

// Each schema compiles on first use: compiling all of them at load held back the server's first answer. compileAll() runs them in tests.
const bodyValidators=new Map<string,ValidateFunction>();function bodyValidator(op:Operation):ValidateFunction{let v=bodyValidators.get(op.name);if(!v){v=ajv.compile(op.bodySchema!);bodyValidators.set(op.name,v);}return v;}

function check(v:ValidateFunction,a:unknown){if(!v(a))throw new UsageError(ajv.errorsText(v.errors,{separator:'; '}));}
function fieldsFor(op:Operation){const properties:Json=Object.fromEntries(op.params.map(p=>[p.key,p.schema]));Object.assign(properties,op.bodySchema?.properties??{});properties.account={type:'string',description:'Exact configured private account profile label; not a tenant or provider account ID.'};if(op.risk!=='read')properties.confirm={type:'boolean',description:'Must be true for the requested mutation or exclusive private output file.'};if(op.bodySchema){properties.payload={...op.bodySchema,description:'Complete native JSON body; do not mix with body flags or payload_file. Arrays use repeated JSON object flags or a whole native array in a private file.'};properties.payload_file={type:'string',minLength:1,description:'Absolute regular non-symlink JSON body file, at most 1 MiB. Cannot mix with payload/body flags.'};}if(op.privateOutput)properties.output_file={type:'string',minLength:1,description:'Required absolute new private file. Exclusive 0600 creation; never overwrites or echoes PNG/embed credentials.'};return{type:'object',properties,required:[...op.params.filter(p=>p.required).map(p=>p.key),...(op.privateOutput?['output_file']:[])],additionalProperties:false};}
async function fileJSON(path:string){let f;try{if(!isAbsolute(path)||(await lstat(path)).isSymbolicLink())throw Error();f=await open(path,constants.O_RDONLY|(constants.O_NOFOLLOW??0));const stat=await f.stat();if(!stat.isFile()||stat.size>1048576)throw Error();return JSON.parse(await f.readFile('utf8'));}catch{throw new UsageError('payload_file must be an absolute regular non-symlink JSON body file, at most 1 MiB.');}finally{await f?.close();}}
function semantics(op:Operation,args:Json,body:any){
 if(op.bodySchema&&(!body||typeof body!=='object'||!Object.keys(body).length))throw new UsageError('Provide a nonempty native request body.');
 if(args.testimonial_id&&(/[\/?#\\]/.test(args.testimonial_id)||['.','..'].includes(args.testimonial_id)||/%2f|%5c|%00/i.test(args.testimonial_id)))throw new UsageError('testimonial_id must be an exact non-traversing ID.');
 if(op.name==='update_testimonial'&&!['approved','add_tags','remove_tags'].some(k=>body[k]!==undefined&&(typeof body[k]!=='object'||body[k].length)))throw new UsageError('Update requires approved, nonempty add_tags or nonempty remove_tags.');
 if(body?.add_tags&&body.remove_tags&&body.add_tags.some((t:string)=>body.remove_tags.includes(t)))throw new UsageError('A tag cannot be added and removed in the same request.');
 for(const key of ['customer_name','form_id','title','text'])if(body?.[key]!==undefined&&!body[key].trim())throw new UsageError('Provided '+key+' cannot be blank.');
 for(const value of [...Object.entries(body??{}).filter(([k])=>/url$|avatar$|logo$/.test(k)).map(([,v])=>v),...(body?.media??[]).map((m:Json)=>m.url)]){let u;try{u=new URL(value as string);}catch{throw new UsageError('Invalid media or source URL.');}if(u.protocol!=='https:'||u.username||u.password)throw new UsageError('Use HTTPS media/source URLs without credentials.');}
 if(body?.recipients&&new Set(body.recipients.map((r:Json)=>r.email.toLowerCase())).size!==body.recipients.length)throw new UsageError('Invite recipient emails must be unique within this request.');
}
async function prepare(op:Operation,args:Json){const flat=Object.fromEntries(Object.keys(op.bodySchema?.properties??{}).filter(k=>args[k]!==undefined).map(k=>[k,args[k]]));if((args.payload!==undefined||args.payload_file!==undefined)&&Object.keys(flat).length)throw new UsageError('Do not mix body flags with payload/payload_file.');if(args.payload!==undefined&&args.payload_file!==undefined)throw new UsageError('Use payload or payload_file, not both.');let body=op.bodySchema?(args.payload_file?await fileJSON(args.payload_file):args.payload??flat):undefined;if(op.bodyRequired&&args.payload===undefined&&!args.payload_file&&!Object.keys(flat).length)throw new UsageError('This operation requires a native body; inspect schema and provide body flags, payload or payload_file.');if(op.bodySchema)check(bodyValidator(op),body);semantics(op,args,body);const path=op.params.filter(p=>p.in==='path').reduce((s,p)=>s.replace('{'+p.name+'}',encodeURIComponent(String(args[p.key]))),op.path);const query:QueryParam[]=op.params.filter(p=>p.in==='query'&&args[p.key]!==undefined).map(p=>({name:p.name,value:args[p.key],explode:p.explode}));return{method:op.method,path,query,body};}
async function execute(op:Operation,args:Json,client:SenjaClient){const call=await prepare(op,args);return client.sanitize(await client.request(call.method,call.path,call.query,call.body,args.account));}
export const ALL_TOOLS:ToolSpec[]=operations.map(op=>({...op,inputSchema:fieldsFor(op),handler:(args,client)=>execute(op,args,client)}));
const account={type:'string',description:'Exact selected private account profile; binds label, not key ownership.'};const confirm={type:'boolean',description:'Explicit approval for this exact requested ordered batch.'};
function helper(name:string,title:string,description:string,risk:Risk,properties:Json,required:string[],handler:ToolSpec['handler']){ALL_TOOLS.push({name,title,description,group:'local_workflows',risk,inputSchema:{type:'object',properties,required,additionalProperties:false},handler});}
helper('list_accounts','List configured accounts','Local profile labels/default/auth method only. No keys, token paths, provider identity or network request.','read',{},[],async(_,c)=>({accounts:c.config.accounts.map(a=>({name:a.name,default:a.name===c.config.defaultAccount,auth:a.apiToken||a.tokenFile?'api_key':'not_configured',credentialSource:a.tokenFile?'token_file':a.apiToken?'private_setting':'not_configured'}))}));
helper('get_operation_schema','Inspect a current native operation','Local reviewed method/path/query/body schema and provenance for one native tool. No credentials or provider request.','read',{operation:{type:'string',enum:operations.map(o=>o.name),description:'Exact native tool name, e.g. update_testimonial or send_invites.'}},['operation'],async a=>({operation:operations.find(o=>o.name===a.operation),source:provenance.source,checked:provenance.checked,snapshotSha256:provenance.sanitizedSnapshotSha256}));
const allowed=operations.filter(o=>o.risk!=='read'&&['testimonials','invites'].includes(o.group)).map(o=>o.name);
const tasks={type:'array',minItems:1,maxItems:20,description:'One to twenty exact ordered supported testimonial/import/invite operations. Invite requests may include up to100 recipients each; review the exact complete recipient list and existing form follow-up sequence.',items:{type:'object',properties:{tool:{type:'string',enum:allowed},arguments:{type:'object',description:'Actual native tool arguments without account, confirm, payload_file or output_file.'}},required:['tool','arguments'],additionalProperties:false}};
function canonical(v:any):any{if(Array.isArray(v))return v.map(canonical);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])]));return v;}
function hash(v:any){return createHash('sha256').update(JSON.stringify(canonical(v))).digest('hex');}
async function reviewed(args:Json,c:SenjaClient){const selected=selectAccount(c.config,args.account);const calls=[];for(const task of args.tasks){if(!allowed.includes(task.tool))throw new UsageError('Unsupported testimonial batch tool.');if(['account','confirm','payload_file','output_file'].some(k=>task.arguments[k]!==undefined))throw new UsageError('Batch arguments cannot override account/confirmation or reference mutable payload files.');const t=ALL_TOOLS.find(t=>t.name===task.tool)!,op=operations.find(o=>o.name===task.tool)!;validateArguments(t,task.arguments);calls.push(await prepare(op,task.arguments));}return{version:1,profile:selected.name,authType:'api_key',snapshotSha256:provenance.sanitizedSnapshotSha256,tasks:args.tasks,calls};}
helper('preview_testimonial_batch','Review exact ordered testimonial tasks','Local validation and SHA-256 of exact ordered testimonial/import/invite work, selected profile label and reviewed schema. No provider reads, key load, identity check, price or rollback guarantee.','read',{tasks,account},['tasks'],async(a,c)=>{const r=await reviewed(a,c);return{...c.sanitize(r)as Json,reviewSha256:hash(r),localOnly:true,providerValidated:false,notice:'Binds profile label and exact requests/order/schema, not key ownership or changing provider state. Each invite request can send up to 100 invite sequences. Preview is local input review, not a real cohort count or provider approval token.'};});
helper('submit_testimonial_batch','Execute reviewed testimonial tasks','Confirmed one-to-twenty ordered testimonial/import/invite tasks. Prevalidate all and verify exact hash before first request. Stop on first failure with known results/failed index/unattempted indices; no retries, rollback or implicit continuation.','destructive',{tasks,account,confirm,review_sha256:{type:'string',pattern:'^[a-f0-9]{64}$',description:'Exact preview_testimonial_batch hash for identical requests, profile label, schema and order.'}},['tasks','review_sha256'],async(a,c)=>{const r=await reviewed(a,c);if(hash(r)!==a.review_sha256)throw new UsageError('Review hash mismatch; preview these exact tasks and selected profile again.');const knownResults:Json[]=[];for(let i=0;i<r.calls.length;i++){const call=r.calls[i]!;try{const result=c.sanitize(await c.request(call.method,call.path,call.query,call.body,r.profile));knownResults.push({index:i,tool:a.tasks[i].tool,result});}catch(e){const err=e as SenjaError;throw new SenjaError(JSON.stringify(c.sanitize({notice:'Batch stopped. Failed request may have an unknown outcome; inspect provider state before repeating. No retries or rollback.',knownResults,failedIndex:i,unattemptedIndices:r.calls.slice(i+1).map((_,j)=>i+1+j),error:err.message})),err.status??0,err.code??'API_ERROR');}}return{requestsProcessed:true,knownResults,notice:'Native requests returned; Invite emails and form follow-up sequences may continue separately. A successful native receipt is not a delivery or consent proof.'};});
const pageOp=operations.find(o=>o.name==='list_testimonials')!;
helper('export_testimonials','Export bounded private testimonials','Confirmed paginated GET export to an exclusive new0600 JSON file. Stop on short native page or local caps. Never downloads media, follows URLs, overwrites files, retries or implies an atomic complete backup.','destructive',{...fieldsFor(pageOp).properties,confirm,start_offset:{type:'integer',minimum:0,maximum:999,description:'Resume inside the first requested page using an export receipt offset and identical filters/page size. Provider state may have changed.'},max_pages:{type:'integer',minimum:1,maximum:100,description:'Local request budget, default10.'},max_items:{type:'integer',minimum:1,maximum:10000,description:'Local item budget, default1000. May stop within a page; receipt records an offset.'},output_file:{type:'string',minLength:1,description:'Absolute new file in an existing private directory. Restrict Windows ACLs separately.'}},['output_file'],async(a,c)=>{
 if(!isAbsolute(a.output_file))throw new UsageError('output_file must be absolute.');
 const maxPages=a.max_pages??10,maxItems=a.max_items??1000,limit=a.limit??100;let page=a.page??1,requests=0,complete=false;const startOffset=a.start_offset??0;if(startOffset>=limit)throw new UsageError('start_offset must be lower than limit.');const testimonials:Json[]=[];let offset=0;let f;try{f=await open(a.output_file,'wx',0o600);}catch{throw new UsageError('Cannot exclusively create output_file.');}
 try{while(requests<maxPages&&testimonials.length<maxItems){const call=await prepare(pageOp,{...a,page,limit});const result=await c.request(call.method,call.path,call.query,call.body,a.account);requests++;if(!Array.isArray(result.testimonials)||!Number.isInteger(result.total)||result.total!==result.testimonials.length||result.total>limit)throw new SenjaError('Invalid native testimonial page receipt; total must count the returned page.');const skip=requests===1?startOffset:0;if(skip>result.total)throw new UsageError('The resume page changed; its requested start_offset no longer exists.');const take=Math.min(result.total-skip,maxItems-testimonials.length);testimonials.push(...result.testimonials.slice(skip,skip+take));offset=skip+take;if(offset<result.total)break;if(result.total<limit){complete=true;break;}page++;offset=0;if(Buffer.byteLength(JSON.stringify(testimonials))>5*1048576)throw new SenjaError('Export exceeds the5MiB local cap; no partial file retained.');}
 const value={testimonials:c.sanitize(testimonials),receipt:{requests,items:testimonials.length,completeWithinRequestedFilters:complete,continuation:complete?null:{page,offset,limit},atomicSnapshot:false}};const bytes=Buffer.from(JSON.stringify(value)+'\n');if(bytes.length>5*1048576)throw new SenjaError('Export exceeds the5MiB local cap; no partial file retained.');await f.writeFile(bytes);return{saved:true,output_file:a.output_file,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),...value.receipt};
 }catch(e){await f.close();f=undefined;await unlink(a.output_file).catch(()=>{});throw e;}finally{await f?.close();}
});
const validators=new Map<string,ValidateFunction>();function validatorFor(tool:ToolSpec):ValidateFunction{let v=validators.get(tool.name);if(!v){v=ajv.compile(tool.inputSchema);validators.set(tool.name,v);}return v;}export function validateArguments(tool:ToolSpec,args:Json){check(validatorFor(tool),args);}
/** Compile every input and body schema, as loading once did, so a test can prove they all compile. */
export function compileAll():number{for(const t of ALL_TOOLS)validatorFor(t);for(const o of operations)if(o.bodySchema)bodyValidator(o);return validators.size+bodyValidators.size;}
export function visibleTools(c:Config){return ALL_TOOLS.filter(t=>!c.readOnly||t.risk==='read');}
